using SithOrange = InOutHelper<
		OnSpark<
			LocalizedClash<
				Lockup<
					Blast<
						TransitionEffect<
							Mix<
								SwingSpeed<600>,
								AudioFlicker<Gradient<Gradient<MistyRose,OrangeRed,OrangeRed,OrangeRed,OrangeRed,OrangeRed,OrangeRed,OrangeRed,OrangeRed,OrangeRed,OrangeRed,OrangeRed,Red>,OrangeRed,OrangeRed,OrangeRed,OrangeRed,OrangeRed,OrangeRed,OrangeRed>,Red>,
								Mix<
									SwingSpeed<800>,
									AudioFlicker<Gradient<Gradient<MistyRose,OrangeRed,OrangeRed,OrangeRed,OrangeRed,OrangeRed,OrangeRed,OrangeRed,OrangeRed,OrangeRed,OrangeRed,OrangeRed,Red>,OrangeRed,OrangeRed,OrangeRed,OrangeRed,OrangeRed,OrangeRed,OrangeRed>,Red>,
									Coral
								>
							>,
							Red,
							TrInstant,
							TrSmoothFade<800>,
							EFFECT_IGNITION
						>,
						BrownNoiseFlicker<White,Strobe<Blue,LemonChiffon,50,1>,300>,
						150,200,600
					>,
					Pulsing<
						Gradient<
							AudioFlicker<Bisque,Orange>,
							HumpFlicker<DarkOrange,Orange,50>,
							HumpFlicker<DarkOrange,Orange,50>,
							HumpFlicker<DarkOrange,Orange,50>,
							BrownNoiseFlicker<White,Strobe<Blue,LemonChiffon,50,1>,300>,
							BrownNoiseFlicker<White,Strobe<Blue,LemonChiffon,50,1>,300>,
							HumpFlicker<DarkOrange,Orange,50>,
							HumpFlicker<DarkOrange,Orange,50>,
							HumpFlicker<DarkOrange,Orange,50>,
							HumpFlicker<DarkOrange,Orange,50>
						>,
						Gradient<
							AudioFlicker<Bisque,Orange>,
							HumpFlicker<DarkOrange,Orange,50>,
							HumpFlicker<DarkOrange,Orange,50>,
							HumpFlicker<DarkOrange,Orange,50>,
							HumpFlicker<DarkOrange,Orange,50>,
							BrownNoiseFlicker<White,Strobe<Blue,LemonChiffon,50,1>,300>,
							BrownNoiseFlicker<White,Strobe<Blue,LemonChiffon,50,1>,300>,
							HumpFlicker<DarkOrange,Orange,50>,
							HumpFlicker<DarkOrange,Orange,50>,
							HumpFlicker<DarkOrange,Orange,50>
						>,
						3500
					>,
					Gradient<
						AudioFlicker<DarkOrange,Orange>,
						AudioFlicker<DarkOrange,Orange>,
						AudioFlicker<DarkOrange,Orange>,
						Gradient<
							AudioFlicker<DarkOrange,Orange>,
							BrownNoiseFlicker<White,Strobe<Blue,LemonChiffon,50,1>,300>,
							BrownNoiseFlicker<White,Strobe<Blue,LemonChiffon,50,1>,300>,
							BrownNoiseFlicker<White,Strobe<Blue,LemonChiffon,50,1>,300>,
							BrownNoiseFlicker<White,Strobe<Blue,LemonChiffon,50,1>,300>,
							MistyRose
						>
					>
				>,
				BrownNoiseFlicker<White,Strobe<Blue,LemonChiffon,50,1>,50>,
			100,50>,
			BrownNoiseFlicker<White,Strobe<Blue,LemonChiffon,50,1>,300>,
		200>,
		200,
		300,
		TransitionEffect<Black,
                     Black,
                     TrConcat<TrInstant,
                              Mix<Bump<Int<0>, Int<3000>>, Black, MistyRose>,
                              TrSmoothFade<4000>,
                              Mix<Bump<Int<0>, Int<3000>>, Black, Orange>,
                              TrSmoothFade<3000>,
                              Mix<Bump<Int<0>, Int<3000>>, Black, OrangeRed>,
                              TrSmoothFade<4000>,
                              Mix<Bump<Int<0>, Int<3000>>, Black, Red>,
                              TrSmoothFade<4000>>,
                     TrInstant,
                     EFFECT_RETRACTION>
	>;